### ISSUE TITLE
Still using mem dependency?

### ISSUE THREAD

**Issue by kolbma** [microlinkhq/html-get#60]
Hi,

are you currently using mem dependency in master?
Can't find it in repository.

With [usage here](https://github.com/microlinkhq/html-get/blob/6451c369f0fc904576b84869e1dcf49132554428/src/index.js#L32) there is a problem, because in 1-day cache maxAge an attacker could put many url-lookups in memory.

**Comment by Kikobeats** [comment]
Hello,

I removed the internal ping functionality in favor of [`@microlink/ping-url`](https://www.npmjs.com/package/@microlink/ping-url), so if you want to reproduce the same behavior just call `pingUrl` and pass the URL to `htmlGet` 🙂

I forgot to remove `mem` from `dependencies`; It has been fixed in the latest patch version (`v2.2.29`)
